### ISSUE TITLE
自定义 log-record.diff-msg-format 结果错误

### ISSUE THREAD

**Issue by duanluan** [qqxx6661/log-record#80]
版本：v1.5.1

`application.yml`:
```yaml
log-record:
  # Diff 时忽略新对象中 null 值字段，默认为 false
  diff-ignore-new-object-null-value: true
  # Diff 格式
  diff-msg-format: 【${_fieldName}】:【${_oldValue}】->【${_newValue}】
  # Diff 分隔符
  diff-msg-separator: ;
```

`UserController`:
```java
@OperationLog(bizId = "#id", bizType = "'user:update'", msg = "'更新用户：' + #_DIFF(#oldObj, #obj)")
public ApiResponse update(@Min(value = 1, message = "参数错误") @PathVariable Long id, @Validated @RequestBody UserUpdateQO obj) {
  User user = userService.getById(id);
  if (user == null) {
    throw new ServiceException("用户不存在");
  }
  LogRecordContext.putVariable("oldObj", user);
  // ……
}
```

`User`:
```java
@LogRecordDiffObject(alias = "用户")
public class User {
  @LogRecordDiffField(alias = "用户名")
  private String username;
  // ……
}
```

`UserUpdateQO`:
```java
@LogRecordDiffObject
public class UserUpdateQO {
  @LogRecordDiffField(alias = "用户名")
  private String username;
  // ……
}
```

结果：`更新用户：?电话?:?18888888887?->?18888888888?;?昵称?:?234?->?23?;?角色?:?2,1671440885033914373?->?2?`

我所有的文件编码都是`UTF-8`。
我试过给`diff-msg-format`的内容前后加单引号也没用。
